config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users
  resources :friendships, only:[:create, :destroy]
  resources :friendship_requests, only:[:create, :destroy]
  resources :checkins, except: [:edit, :update]

  get '/signup' => 'users#new'
  get '/users/show' => 'users#show'
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/about' => 'welcome#about'
  get '/contact' => 'welcome#contact'
  get '/developers' => 'welcome#developers'

  namespace :api do
    resources :users,only: [:index, :show], defaults: {format:"json"}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  

  has_many :friendship_requests
  has_many :pendingfriends, through: :friendship_requests
  has_many :request_made, class_name: FriendshipRequest
  has_many :request_received, class_name: FriendshipRequest, foreign_key: :friendee_id

#   def requests
#     create a method that will query the database where current_user.id equal to friendee.id
#     @requests = friendship_requests.where(friendee_id: self.id).map(&:user).map(&:name)

#   end

  has_many :friendships
  has_many :friends, through: :friendships

  has_and_belongs_to_many :checkins
  has_secure_password


  def add_friend(friendee)
    self.friendships.create({:friendee_id => friendee.id, :user_id => self.id})
  end

  def accept_friend(user)
    self.friendships.create({:friendee_id => user.id, :user_id=> user.id})
  end

# this defines all the friends as an array when called on the user class

# HAVE TESTS to test if self.friendship could work.....


  def friends
    @friends_arr = []
    current_user = User.where(id: self.id)
    friends = current_user[0].friendships
    friends.each do |f|
      @friends_arr.push(f.friendee)
    end
   
    @friends_arr
  end

# this defines people that i have sent requests to so they cannot be possible friends anymore

  def requesters
    @requesters_arr = []
    current_user= User.where(id: self.id)
    requesters = current_user[0].friendship_requests
    requesters.each do |r|
      @requesters_arr.push(r.friendee)
    end

    @requesters_arr
    

  end  

# this defines people that have sent requests to me so they cannot be possible friends anymore

  def requestees
    @requestees_arr = []
    current_user= User.where(id: self.id)
    requestees = current_user[0].request_received

    requestees.each do |r|
      @requestees_arr.push(r.user)
    end

    @requestees_arr
    

  end

# this defines all possible friends

  def possible_friends
    User.all - self.requesters - self.requestees-self.friends-User.where(id:self.id)
  end 

  def as_json(option={})
  # pass in the array of attribute you dont want to show
  # :methods=>[:friends]
    super(:except => [:password_digest, :created_at, :updated_at, :avatar, :oid], :include=>[:friendships, :checkins])
    # can replace except with only which is inverse
    # the method is defined top and it will be returned in the json
  end


  # mount_uplader is used for carrierwave
  mount_uploader :avatar, AvatarUploader
  attr_reader :password


  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/api/users_controller.rb
module API
  class UsersController < ApplicationController
    protect_from_forgery with: :null_session
    respond_to :json

    def index
      users = User.all

      respond_with users
    end

    def show
      user = User.find(params[:id])

      respond_with user
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if params[:query]
      # [:query] defined in view as filter input field
      @users = User.where(name:/#{params[:query]}/i)
    else
      @users = User.all
    end 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to root_path
    else
      flash[:notice] = "Error Signing up. Please try again."
      redirect_to root_path
      # render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to users_path
    else 
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else
      redirect_to users_path(@user)
    end
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :city, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class='container'>
  <button type="button" class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Logout", logout_path, method: :delete %></button>
  <button type="button" class="btn btn-info btn-register btn-lg nav-links" data-toggle="modal" data-target="#editUserModal">Edit Profile</button>  
  <button class="btn btn-info btn-register btn-lg nav-links" ><%=link_to "Check in", new_checkin_path  %></button>
  <button class="btn btn-lg btn-info btn-register nav-links"><%= link_to "Your Profile", user_path(current_user)%></button>
  <button type="button" class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Home", root_path %></button>
</div>

<div class='container-fluid'>
  <div class='col-md-4'>
    <h2>Possible friends</h2>
    <% current_user.possible_friends.each do |f|%>
      <%= image_tag f.avatar.url(:thumb) %>
      <br>
      <div class="form-font"><%= f.name%></div>
      <div class="form-font"> <%= link_to "Request to be friends", friendship_requests_path(:friendee_id => f.id), :method=>:post %></div>
    <% end %>
  </div>

  <div class='col-md-8'>
    <h2>What people are up to</h2>
      <div>
        <% @users.each do |u| %>
          <%= link_to u.name, user_path(u.id)%>
          <br>
          <% u.checkins.each do |c| %>
            <h4><%= c.name %><br></h4>
            <%= image_tag c.photo.url(:photo) %>
            <br>
          <% end %>
        <% end %>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container-fluid'>
  <div class="nav">
    <button class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Log Out", logout_path, method: :delete%></button>

    <button class="btn btn-info btn-register btn-lg nav-links" data-toggle="modal" data-target="#editUserModal">Edit Profile</button>

    <button class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Back Home", root_path %></button>
  </div>  

  <h1>More about <%= @user.name %></h1>

  <%= image_tag @user.avatar.url(:thumb) %>
   
  <!-- ============ Start Edit User Modal ============ -->
    <div class="modal fade" id="editUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-med">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="modal-title" id="myModalLabel">Edit Your Profile</h2>
          </div>

          <div class="modal-body">
            <%= bootstrap_form_for current_user, url: user_path(current_user), method: :patch do |f| %>
              <%= f.text_field :name, label: "Name:", class: "form-font" %>
              <%= f.email_field :email, label: "Email:", class: "form-font" %>
              <%= f.password_field :password, label: "Password:", class: "form-font" %>
              <%= f.password_field :password_confirmation, label: "Password Confirmation:", class: "form-font" %>
              <%= f.text_field :city, label: "Your city:", class: "form-font" %>
              <%= f.file_field :avatar %>

              <%= f.submit "Save Changes!" %>
            <% end %>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div> <!-- end modal content div-->
      </div> <!-- end modal dialog div-->
    </div> <!-- end edit user modal -->

  <!-- ============ Start Checkins Modal This doesn't work moved to checkins/new view ============ -->
    <div class="modal fade" id="checkInUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-med">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Check In</h4>
          </div>

          <div class="modal-body">
            <div class="row map-container">
              <input id="pac-input" class="controls" type="text" placeholder="Search Box - Enter Address or Venue Name">
              <div id="map-canvas" class="centered"></div>
            </div>

            <%= bootstrap_form_for :checkin, url: {:controller=> 'checkins', :action => "create"}  do |f| %>
              <%= f.file_field :photo, label: "Photo:" %>
              <%= f.text_area :status, label: "What's happenin?" %>
              <!-- content in this div is appended from google maps ajax request and solely input here to save to db -->
              <div class='hide'>
                <%= f.text_area :name, :id => 'name' %>
                <%= f.text_area :longitude, :id => 'longitude' %>
                <%= f.text_area :latitude, :id => 'latitude'  %>
                <%= f.text_area :formatted_address, :id => 'address' %>
                <%= f.text_area :types, :id => 'type' %>
              </div>
              <%= f.submit "Check me in!" %>
            <% end %>
            <%= link_to "Cancel", root_path %>
          </div> <!-- end modal body div-->

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div> <!-- end modal content div-->
      </div> <!-- end modal dialog div-->
    </div> <!-- end checkin modal -->


  <!-- ============ User Friends Modal ============ -->
    <!-- shows all user's friends -->
    <button class="btn btn-primary user-modal" data-toggle="modal" data-target="#userFriendsModal"><%= @user.name %>'s Friends</button>
    <div class="modal fade" id="userFriendsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-med">
        <div class="modal-content">
          <div class="modal-header">
            <h2><%= @user.name %>'s Friends</h2>
          </div>

          <div class="modal-body">
            <% @user.friendships.each do |friendship| %>
              <%= image_tag friendship.friendee.avatar.url(:thumb) %>
              <h3><%= link_to friendship.friendee.name, user_path(friendship.friendee)%></h3>
              <p>Friends since: <%= friendship.created_at.localtime.strftime("%B %d, %Y") %></p>
              <%= link_to "delete friend", friendship, :method => :delete %>
              <hr>
            <% end %>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div> <!-- end modal content div-->
      </div> <!-- end modal dialog div-->
    </div> <!-- end edit user modal -->

  <!-- ============ Incoming Friend Requests Modal============ -->
    <!-- shows who have sent requests to the current_user -->
    <button class="btn btn-primary user-modal" data-toggle="modal" data-target="#incomingFriendRequests">Incoming Friend Requests</button>
    <div class="modal fade" id="incomingFriendRequests" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-med">
        <div class="modal-content">
          <div class="modal-header">
            <h2>Pending Friends</h2>
          </div>

          <div class="modal-body">
            <% current_user.request_received.each do |request| %>
              <%= image_tag request.user.avatar.url(:thumb) %>
              <%= link_to request.user.name, user_path(request.user) %>
              <%= link_to "accept", friendship_request_path(request,:accept => true), :method => :delete %>
              <%= link_to "decline", friendship_request_path(request), :method => :delete %>
              <% end %>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div> <!-- end modal content div-->
      </div> <!-- end modal dialog div-->
    </div> <!-- end edit user modal -->

<!-- ============ User Pending Friends Modal============ -->
    <!-- shows who you have sent requests to -->
    <button class="btn btn-primary user-modal" data-toggle="modal" data-target="#pendingRequestsModal">Pending Friend Requests</button>
    <div class="modal fade" id="pendingRequestsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-med">
        <div class="modal-content">
          <div class="modal-header">
            <h2>Incoming Friend Requests</h2>
          </div>

          <div class="modal-body">
            <% current_user.friendship_requests.each do |request| %>

            <%= image_tag request.friendee.avatar.url(:thumb) %>
            <%= link_to request.friendee.name, user_path(request.friendee)%>
            <%= link_to "cancel", friendship_request_path(request), :method=>:delete %>

            <% end %>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div> <!-- end modal content div-->
      </div> <!-- end modal dialog div-->
    </div> <!-- end edit user modal -->

    <!-- shows all users's checkins -->
    <h2><%= @user.name %>'s Previous Check Ins</h2>
      <div class='checkin'>
        <% @user.checkins.each do |checkin| %>
          <li id="checkin-name"><h3><%= image_tag "https://s3-us-west-1.amazonaws.com/carrierwave-tony/checkin.png", height: 30 %> <%= checkin.name %></h3></li>
          <li><%= checkin.created_at.localtime.strftime("%d %b. %Y at %l:%M %P") %></li>
          <li><%= image_tag checkin.photo.url(:photo) %></li>
          <li><%= checkin.status %></li>
        <% end %>
      </div>
  </div>
</div>