config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :users
  resources :friendships, only:[:create, :destroy]
  resources :friendship_requests, only:[:create, :destroy]
  resources :checkins, except: [:edit, :update]

  get '/signup' => 'users#new'
  get '/users/show' => 'users#show'
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/about' => 'welcome#about'
  get '/contact' => 'welcome#contact'
  get '/developers' => 'welcome#developers'

  namespace :api do
    resources :users,only: [:index, :show], defaults: {format:"json"}
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def developers
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="pages">
  <h2>About What's Happenin</h2>
  <hr>
  <p>Nulla facilisi. Cras id dui. Aenean ut eros et nisl sagittis vestibulum. Duis leo. Sed cursus turpis vitae tortor.

  Curabitur a felis in nunc fringilla tristique. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Aliquam eu nunc. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi.</p>

  <button class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Back Home", root_path %></button>
</div>

app/views/welcome/contact.html.erb
<div class="pages">
  <h2>Contact the developers</h2>
  <hr>
  <p>Nulla facilisi. Cras id dui. Aenean ut eros et nisl sagittis vestibulum. Duis leo. Sed cursus turpis vitae tortor.

  Curabitur a felis in nunc fringilla tristique. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Aliquam eu nunc. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi.</p>

  <button class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Back Home", root_path %></button>
</div>

app/views/welcome/developers.html.erb
<div class="pages">
  <h2>What's Happenin Documentation for Developers</h2>
  <hr>
  <p>Nulla facilisi. Cras id dui. Aenean ut eros et nisl sagittis vestibulum. Duis leo. Sed cursus turpis vitae tortor.

  Curabitur a felis in nunc fringilla tristique. Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Aliquam eu nunc. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus leo dolor, tempus non, auctor et, hendrerit quis, nisi.</p>

  <a href="/api/users">Click Here for the What's Happenin' API.</a>
  
  <button class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Back Home", root_path %></button>
</div>

app/views/welcome/index.html.erb
<!-- ============== HEADER ============== -->
<div id="h">
	<div class="container">
		<div class="row">
			<div class="flash-notice">
				<% if flash[:notice] %>
					<%= flash[:notice] %>
				<% end %>
			</div>

			<!-- ============== USER SIGN UP AND LOG IN TOP NAV BAR============== -->
			<% if !logged_in? %>
        <div class="nav-users">
	        <a href="#loginModal" data-toggle="modal">Log In</a>
	        <a href="#newUserModal" data-toggle="modal">Sign Up</a>
        </div>

				<!-- ============== Log In Modal ============== -->
				<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog modal-med">
				    <div class="modal-content">
				      <div class="modal-header">
				      	<h2>Log In To What's Happenin'</h2>
				      </div>

				      <div class="modal-body form-align"> 
					      <div class="users-form">
					      	<%= bootstrap_form_for :login, url: login_path  do |f| %>
							      <%= f.text_field :email, label: "Email:", class: "form-font" %>
							      <%= f.password_field :password, label: "Password:", class: "form-font" %>

							      <%= f.submit 'Log In', class: "btn btn-info" %>
						    <% end %>
						    </div>
				      </div>

				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				      </div>
				    </div> <!-- end modal content div -->
				  </div> <!-- end modal dialog div -->
				</div> <!-- end log in modal -->

				<!-- ============== Sign Up Modal ============== -->
				<div class="modal fade" id="newUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog modal-med">
				    <div class="modal-content">
				      <div class="modal-header">
				        <h2>Sign Up For What's Happenin'</h2>
				      </div>

				      <div class="modal-body form-align">
				      	<div class="users-form">
					      		<%= bootstrap_form_for :user, url: {:controller=> 'users', :action => "create"} do |f| %>
								    <%= f.text_field :name, label: "Name:", class: "form-font" %>
								    <%= f.email_field :email, label: "Email:", class: "form-font" %>
								    <%= f.password_field :password, label: "Password:", class: "form-font" %>
								    <%= f.password_field :password_confirmation, label: "Password Confirmation:", class: "form-font" %>
								    <%= f.text_field :city, label: "Your city:", class: "form-font" %>
								    <%= f.file_field :avatar %>

								    <%= f.submit "Sign me up!", class: "btn btn-info" %>
						  		<% end %>
					  		</div>
				      </div>

				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				      </div>
				    </div> <!-- end modal content div -->
				  </div> <!-- end modal dialog div -->
				</div> <!-- end sign up modal -->
      <% end %> <!--- end !logged_in? -->

			<!-- ============== USERS WHO HAVE SIGNED IN ============== -->
      <% if logged_in? %>
				<div class='login-nav'>
          <button class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Log Out", logout_path, method: :delete%></button>

          <button class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Friends", users_path%></button>

          <button class="btn btn-info btn-register btn-lg nav-links" data-toggle="modal"><%= link_to "Check In", new_checkin_path %></button>

          <button class="btn btn-info btn-register btn-lg nav-links"><%= link_to "Your Profile", user_path(current_user)%></button>
        </div>

        <!-- ============== Start Edit User Modal ============== -->
				<div class="modal fade" id="editUserModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				  <div class="modal-dialog modal-med">
				    <div class="modal-content">

				      <div class="modal-header">
				        <h2 class="modal-title" id="myModalLabel">Edit Your Profile</h4>
				      </div>

				      <div class="modal-body">
				      	<%= bootstrap_form_for current_user, url: user_path(current_user), method: :patch do |f| %>
							    <%= f.text_field :name, label: "Name:", class: "form-font" %>
							    <%= f.email_field :email, label: "Email:", class: "form-font" %>
							    <%= f.password_field :password, label: "Password:", class: "form-font" %>
							    <%= f.password_field :password_confirmation, label: "Password Confirmation:", class: "form-font" %>
							    <%= f.text_field :city, label: "Your city:", class: "form-font" %>
							    <%= f.file_field :avatar %>

							    <%= f.submit "Save Changes!" %>
					  		<% end %>
				      </div>

				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				      </div>

				    </div> <!-- end modal content div -->
				  </div> <!-- end modal diaglog div -->
				</div> <!-- end edit user modal -->
     	<% end %> <!-- end logged_in? -->

<!-- ============== HEADER TITLE CONTENT ============== -->
	    <div class="col-md-10 col-md-offset-1 title">
	    	<h1>WHAT'S HAPPENIN?</h1>
	    	<h5 class="descript">Enter your location below to see what's happenin near you</h5>
	    </div>
		</div> <!-- end class row-->

<!-- ============== GOOGLE MAP ============== -->
    <div class="row map-container land-page">
    	<div>
    		<input id="pac-input" class="controls" type="text" placeholder="Search your location - enter an address or venue">
      <div id="map-canvas" class="centered"></div>
    </div>

    <div class="row instaDiv">	
    	<ul id="picture-feed">  
    	</ul>
    </div>
	</div> <!--/container -->
</div> <!--/H -->

<!-- ============== ABOUT WHAT'S HAPPENIN ============== -->
<div id="w">
	<div class="row">
		<div class='container-fluid wh'>
			<h4 class='wh-title'>What's Happenin?</h4>
			<div class='col-md-3 wh-div'>
				<%= image_tag "https://s3-us-west-1.amazonaws.com/carrierwave-tony/party.jpg", height: 200, width: 300 %>
				<p>Take the OMO out of FOMO with What's Happenin'. Find out what's going on in your area in real time so you never feel left out again.</p>
			</div>

			<div class='col-md-3 wh-div'>
				<%= image_tag "https://s3-us-west-1.amazonaws.com/carrierwave-tony/bar.jpg?", height: 200, width: 300 %>
				<p>Don't know what to do on a Friday night? Before you check out that new venue nearby, look to see who's already there and what's happenin.</p>
			</div>

			<div class='col-md-3 wh-div'>
				<%= image_tag "https://s3-us-west-1.amazonaws.com/carrierwave-tony/city.png", height: 200, width: 300 %>
				<p>See geotagged Instagram posts in one place, check in to all of the hottest spots in town, and keep track of your favorite places.</p>
			</div>

			<div class='col-md-3 wh-div'>
				<%= image_tag "https://s3-us-west-1.amazonaws.com/carrierwave-tony/friends.png", height: 200, width: 300 %>
				<p>Find and add new friends directly on What's Happenin' so you can keep in touch and see what other hot spots you might want to check out.</p>				
			</div>
	</div> <!-- /container -->
</div> <!-- /W -->

<!-- ============== FOOTER ============== -->
<div id="f">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 centered footer-ul">
				<h4 class="gray">Get to know us.</h4>
				<ul>
					<li><%= link_to "About Us", about_path %></li>
					<li><%= link_to "Contact Us", contact_path%></li>
					<li><%= link_to "Developers", developers_path%></li>
				</ul>

				<h4 class="mb gray">Find us on social media.</h4>
				<ul>
					<li><%= image_tag "https://s3-us-west-1.amazonaws.com/carrierwave-tony/fb.png" %></li>
					<li><%= image_tag "https://s3-us-west-1.amazonaws.com/carrierwave-tony/twitter.png" %></li>
					<li><%= image_tag "https://s3-us-west-1.amazonaws.com/carrierwave-tony/gplus.png" %></li>
					<li><%= image_tag "https://s3-us-west-1.amazonaws.com/carrierwave-tony/pinterest.png" %></li>
				</ul>
			</div>
		</div> <!--r /ow -->
	</div> <!-- /container -->
</div> <!-- /F -->

<!-- ============== CREDITS ============== -->
<div id="c">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3 centered">
				<p>Copyright 2015 | JKTZ &#9829;</p>
			</div>
		</div>
	</div> <!-- /container -->
</div> <!-- /C -->